# Generated by Django 3.2.19 on 2023-11-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0010_auto_20231106_0956'),
    ]

    operations = [
        
        
        ]
