# Generated by Django 3.2.19 on 2023-11-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_bankmodel_sale_transaction_sales_item_salesorder'),
    ]

    operations = [
        
    ]
