# Generated by Django 3.2.19 on 2023-11-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0012_sales_item_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=100, null=True)),
                ('orderno', models.IntegerField(null=True)),
                ('orderdate', models.DateField(null=True)),
                ('duedate', models.DateField(null=True)),
                ('placeofsupply', models.CharField(max_length=100, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=100)),
                ('UPI', models.CharField(max_length=100, null=True)),
                ('checkno', models.CharField(max_length=100, null=True)),
                ('subtotal', models.CharField(max_length=100, null=True)),
                ('IGST', models.CharField(max_length=100, null=True)),
                ('CGST', models.CharField(max_length=100, null=True)),
                ('SGST', models.CharField(max_length=100, null=True)),
                ('taxamount', models.CharField(max_length=100, null=True)),
                ('adjustment', models.CharField(max_length=100, null=True)),
                ('grandtotal', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(null=True)),
                ('paid', models.CharField(max_length=100, null=True)),
                ('balance', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='sales')),
                ('status', models.CharField(default='open', max_length=100)),
                ('action', models.CharField(default='convert to invoice', max_length=100)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='sales_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('cmp', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('sale_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='sale_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesorder')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_num', models.PositiveBigIntegerField(null=True)),
                ('ifsc', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('upi_id', models.CharField(max_length=255)),
                ('as_of_date', models.DateField(null=True)),
                ('card_type', models.CharField(max_length=255)),
                ('open_balance', models.BigIntegerField(null=True)),
                ('current_balance', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
