# Generated by Django 3.2.19 on 2023-11-29 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_bankmodel_sale_transaction_sales_item_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company'),
        ),
    ]
