# Generated by Django 3.2.19 on 2023-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0014_salesorder_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='accno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
