# Generated by Django 3.2.19 on 2023-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0015_salesorder_accno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_item',
            name='product',
        ),
        migrations.AddField(
            model_name='sales_item',
            name='product1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
