# Generated by Django 3.2.19 on 2023-11-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0016_auto_20231130_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
    ]
