# Generated by Django 3.2.19 on 2023-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_sales_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_item',
            name='product1',
        ),
    ]
